title: Kaylea - for the love of barcharts
description: A place to dabble in a bit of data visualisations

theme: jekyll-theme-minimal

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"

# Build settings
markdown: kramdown