title: Kaylea - for the love of barcharts
description: A place to dabble in a bit of data visualisations

remote_theme: pages-themes/cayman@v0.2.0

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"

# Build settings
markdown: kramdown